engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "routes/*.js"
  - "routes/**/*.js"
  - "routes/**/*.js"
exclude_paths:
- node_modules/
- startup/db/
- UI/