language: node_js
node_js:
 - "10.11.0"
services:
  - postgresql
before_script:
  - psql -c "CREATE USER mchardex WITH PASSWORD 'h0ttestt';" -U postgres
  - psql -c 'DROP DATABASE IF EXISTS travis_ci_test;' -U postgres
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
script:
  - npm test
after_success:
  - npm run coverage
  - npm run report-coverage
  - npm run codeclimate-report
