language: node_js
env:
- NODE_ENV=test
node_js:
 - "stable"
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
services:
  - postgresql
before_script:
  - psql -c "CREATE USER mchardex WITH PASSWORD 'h0ttestt';" -U postgres
  - psql -c 'DROP DATABASE IF EXISTS question_test;' -U postgres
  - psql -c 'CREATE DATABASE question_test;' -U postgres
script:
  - npm test
after_success:
  - npm run coverage
  - npm run report-coverage
  - npm run codeclimate-report
